spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    username: sa
    url: jdbc:sqlite:memory:myDb?cache=shared
    password: sa
  jpa:
    properties:
      hibernate:
        dialect:
          nodeValue: org.hibernate.community.dialect.SQLiteDialect
          format_sql: 'true'
    hibernate:
      ddl-auto: update
  application:
    name: Ejercicio
server:
  port: '8080'
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
